---
# Копируем конфиги из шаблона

- name: Копируем конфиг filebeat
  template:
    src=filebeat.yml.j2
    dest=/etc/filebeat/filebeat.yml
    owner=root
    group=elasticsearch
    mode=0660
  become: true
